name: html_character_entities
description: >-
  A utility class containing maps of every HTML 4.01 character entity,
  including ASCII and hex codes, and methods to encode/decode strings
  with those character entities.
version: 1.0.0+1
homepage: https://github.com/james-alex/html_character_entities

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
