name: html_character_entities
description: >-
  A utility class containing maps of every HTML 4.01 character entity,
  including ASCII and hex codes, and methods to encode/decode strings
  with those character entities.
version: 0.1.1+1
author: James Alexander <j.alex@email.com>
homepage: https://github.com/james-alex/html_character_entities

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5
